<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Vortice.Direct3D12" Version="3.8.3" />
    <PackageReference Include="Vortice.DXGI" Version="3.8.3" />
    <ProjectReference Include="..\..\tools\ShaderConvention\ShaderConvention.csproj"
                  PrivateAssets="all" />
  </ItemGroup>
  <Target Name="CompileShaders" AfterTargets="Build">
    <Exec Command="dotnet run --project &quot;$(MSBuildProjectDirectory)\..\..\tools\ShaderCompiler\ShaderCompiler.csproj&quot; -- &quot;$(TargetPath)&quot; &quot;$(MSBuildProjectDirectory)&quot; &quot;$([System.IO.Path]::GetDirectoryName($(TargetPath)))&quot;" />
  </Target>
</Project>
